In [2]:
import torch
import numpy as np

a = torch.tensor([[0.1, 0.2],[0.3, 0.4]])
a.shape

torch.Size([2, 2])

In [2]:
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]])

In [3]:
b = torch.tensor([[0.1, 0.2],[0.3, 0.4],[0.5, 0.6]])
b

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [0.5000, 0.6000]])

In [4]:
b.shape

torch.Size([3, 2])

In [5]:
c = torch.tensor([[[0.1],[0.2]],[[0.3],[0.4]]])
c.shape

torch.Size([2, 2, 1])

In [6]:
a = torch.tensor(np.array([[0.1, 0.2],[0.3, 0.4]]))
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]], dtype=torch.float64)

In [7]:
a.shape

torch.Size([2, 2])

In [8]:
a = np.array([1, 2, 3, 4, 5])
tensor_a = torch.from_numpy(a)
tensor_a

tensor([1, 2, 3, 4, 5])

In [9]:
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float32)
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]])

In [10]:
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float64)
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]], dtype=torch.float64)

In [11]:
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float16)
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.3999]], dtype=torch.float16)

<h2 style="text-align: center; direction: rtl;">
יצירת טנזורים בצורה רנדומלית
</h2>
<h3 style="text-align: center; direction: rtl;">
בנוסף יצירת טנזור אפסים ואחדים
</h3>

In [12]:
r = torch.rand(2,2,2)
r

tensor([[[0.0874, 0.5156],
         [0.2353, 0.2169]],

        [[0.0411, 0.3265],
         [0.4758, 0.4059]]])

In [13]:
r.shape

torch.Size([2, 2, 2])

In [14]:
zeros = torch.zeros(2,2,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [15]:
zeros.shape

torch.Size([2, 2, 3])

In [16]:
ones = torch.ones(2,2,3)
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [17]:
ones.ndim

3

In [18]:
i = torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
i.shape

torch.Size([3, 3])

In [20]:
f = torch.full((3,3,2), 0.42)
f

tensor([[[0.4200, 0.4200],
         [0.4200, 0.4200],
         [0.4200, 0.4200]],

        [[0.4200, 0.4200],
         [0.4200, 0.4200],
         [0.4200, 0.4200]],

        [[0.4200, 0.4200],
         [0.4200, 0.4200],
         [0.4200, 0.4200]]])

In [21]:
lin = torch.linspace(0, 20, steps=5)
lin

tensor([ 0.,  5., 10., 15., 20.])

In [22]:
log = torch.logspace(-3, 3, steps=4)
log

tensor([1.0000e-03, 1.0000e-01, 1.0000e+01, 1.0000e+03])

In [23]:
a = torch.tensor([[0.5, 0.5],[0.5, 0.5]])
b = torch.zeros_like(a)
b

tensor([[0., 0.],
        [0., 0.]])

In [24]:
c = torch.ones_like(a)
c

tensor([[1., 1.],
        [1., 1.]])

In [25]:
i = torch.tensor([[1,2],[3,4]])
i.dtype

torch.int64

In [26]:
i = torch.tensor([[1,2],[3,4]], dtype=torch.int32)
i

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [27]:
a = torch.arange(1,10, step=2)
a

tensor([1, 3, 5, 7, 9])

<div dir="rtl" style="margin-left: -3cm;">

### יצירת תמורה אקראית (Random Permutation)

הפקודה `torch.randperm(n)` יוצרת טנזור המכיל את כל המספרים השלמים בטווח שבין **0** ל - **n-1** בסדר אקראי.

בניגוד להגרלת מספרים רגילה 
(`randint`), כאן מובטח שכל מספר יופיע **בדיוק פעם אחת** (ללא חזרות).

**שימוש נפוץ:** ערבוב אינדקסים (Shuffling) של דאטה-סט לפני אימון.

</div>

In [28]:
r = torch.randperm(10)
r

tensor([6, 4, 7, 5, 8, 1, 3, 9, 0, 2])

### Tensor Munging Operations

כלומר גישה לאלמנט מסויים בטנזור


In [29]:
a = torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [30]:
a[0][0]

tensor(1)

In [31]:
a[0][1]

tensor(2)

In [32]:
a[1][0]

tensor(3)

In [33]:
a[1][1]

tensor(4)

In [34]:
a.shape

torch.Size([2, 2])

In [35]:
a = torch.zeros(10)
a

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
b = a.view(2,5)
b

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [37]:
a = torch.arange(1,10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b = a.view(3,3)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
b.shape

torch.Size([3, 3])

<div dir="rtl" style="margin-left: -3cm;">

### Cat 

פעולת CAT משרשרת טנזורים

כאשר משתנה ראשון של הפונקציה זה רשימת הטנזורים לצורך השרשור

והמשתנה השני של הפונקציה CAT זה המימד של הנזור.

בדוגמה הבאה נשים לב כי למעשה המימד הוא 2 של הטנזור,
כלומר ניתן לשרשר עמודות או שורות.


כאשר שרשור שורות יהיה מימד אפס ואז המטריצות (טנזורים) ישורשרו בטור אחד לשני.

לעומת זאת עם נבחר 1 במימד אזי נקבל שרשור עמודי כלומר מטריצה מעל מטריצה.

סך הכל נקבל הבדל של אוגמנטציה עמודה או שורה
</div>


### Cat 

פעולת CAT משרשרת טנזורים

כאשר משתנה ראשון של הפונקציה זה רשימת הטנזורים לצורך השרשור

והמשתנה השני של הפונקציה CAT זה המימד של הנזור.

בדוגמה הבאה נשים לב כי למעשה המימד הוא 2 של הטנזור,
כלומר ניתן לשרשר עמודות או שורות.


כאשר שרשור שורות יהיה מימד אפס ואז המטריצות (טנזורים) ישורשרו בטור אחד לשני.

לעומת זאת עם נבחר 1 במימד אזי נקבל שרשור עמודי כלומר מטריצה מעל מטריצה.

סך הכל נקבל הבדל של אוגמנטציה עמודה או שורה
</div>

In [61]:
a = torch.zeros(2,2)
a

tensor([[0., 0.],
        [0., 0.]])

In [62]:
a.shape

torch.Size([2, 2])

In [63]:
b = torch.cat([a,a,a],0)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [64]:
b.shape

torch.Size([6, 2])

The stack operation 

בשונה מהפעולה  שראינו קודם

(CAT)

הפעם השרשור מגדיל את מימד הטנזור

<div dir="rtl" style="display: flex; justify-content: center; align-items: center; width: 100%;"><div style="text-align: center;">
Cat vs Stack - טבלת השוואה
פעולת CAT משרשרת טנזורים לאורך ממד קיים, בעוד פעולת STACK יוצרת ממד חדש.

<table border="1" cellpadding="10" cellspacing="0" style="border-collapse: collapse; text-align: center; margin: 0 auto;"> <tr style="background-color: #4a4a4a; color: white;"> <th>פעולה</th> <th>מה עושה</th> <th>שינוי במימדים</th> <th>צורה מקורית</th> <th>dim=0</th> <th>dim=1</th> <th>dim=2</th> </tr> <tr style="background-color: #e6f3ff;"> <td><strong>CAT</strong></td> <td>משרשר לאורך ממד קיים</td> <td>לא מוסיף ממד</td> <td>[2, 2]</td> <td>[6, 2]<br/>שרשור שורות</td> <td>[2, 6]<br/>שרשור עמודות</td> <td>—</td> </tr> <tr style="background-color: #fff3e6;"> <td><strong>STACK</strong></td> <td>מערים ויוצר ממד חדש</td> <td>מוסיף ממד</td> <td>[2, 1]</td> <td>[3, 2, 1]<br/>ממד חדש בהתחלה</td> <td>[2, 3, 1]<br/>ממד חדש באמצע</td> <td>[2, 1, 3]<br/>ממד חדש בסוף</td> </tr> </table><br/>
דוגמה ויזואלית - CAT
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; text-align: center; margin: 0 auto;"> <tr style="background-color: #4a4a4a; color: white;"> <th>מקור [2,2]</th> <th>dim=0 → [6,2]</th> <th>dim=1 → [2,6]</th> </tr> <tr> <td style="font-family: monospace;"> [[0, 0],<br/> [0, 0]] </td> <td style="font-family: monospace; background-color: #e6f3ff;"> [[0, 0],<br/> [0, 0],<br/> [0, 0],<br/> [0, 0],<br/> [0, 0],<br/> [0, 0]]<br/> <small>↓ שרשור אנכי</small> </td> <td style="font-family: monospace; background-color: #e6ffe6;"> [[0, 0, 0, 0, 0, 0],<br/> [0, 0, 0, 0, 0, 0]]<br/><br/> <small>→ שרשור אופקי</small> </td> </tr> </table><br/>
דוגמה ויזואלית - STACK
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; text-align: center; margin: 0 auto;"> <tr style="background-color: #4a4a4a; color: white;"> <th>מקור [2,1]</th> <th>dim=0 → [3,2,1]</th> <th>dim=1 → [2,3,1]</th> <th>dim=2 → [2,1,3]</th> </tr> <tr> <td style="font-family: monospace;"> [[0],<br/> [0]] </td> <td style="font-family: monospace; background-color: #fff3e6;"> [[[0],[0]],<br/> [[0],[0]],<br/> [[0],[0]]]<br/> <small>3 במיקום 0</small> </td> <td style="font-family: monospace; background-color: #ffe6f3;"> [[[0],[0],[0]],<br/> [[0],[0],[0]]]<br/><br/> <small>3 במיקום 1</small> </td> <td style="font-family: monospace; background-color: #e6ffe6;"> [[[0,0,0]],<br/> [[0,0,0]]]<br/><br/> <small>3 במיקום 2</small> </td> </tr> </table><br/>
כלל הזהב 🔑
<table border="2" cellpadding="15" style="border-collapse: collapse; background-color: #ffffd9; margin: 0 auto;"> <tr> <td> <strong>CAT:</strong> מרחיב ממד קיים → [2,2] עם 3 טנזורים ו-dim=0 → [<span style="color:red;">6</span>,2]<br/><br/> <strong>STACK:</strong> יוצר ממד חדש → [2,1] עם 3 טנזורים ו-dim=0 → [<span style="color:red;">3</span>,2,1] </td> </tr> </table></div></div>

In [65]:
a = torch.zeros(2,1)
a

tensor([[0.],
        [0.]])

In [66]:
b = torch.stack([a,a,a], 0)
b.shape

torch.Size([3, 2, 1])

In [67]:
b = torch.stack([a,a,a], 1)
b.shape

torch.Size([2, 3, 1])

In [68]:
b = torch.stack([a,a,a], 2)
b.shape

torch.Size([2, 1, 3])

The chunk operation chops up a tensor into the given number of parts along a given direction. 

Note that the first parameter is the tensor; 

the second parameter is the number of parts; 

and the third parameter is the direction along which to partition. 

<div dir="rtl" style="display: flex; justify-content: center; align-items: center; width: 100%;"><div style="text-align: center;">

<h3>Chunk vs Split - טבלת השוואה</h3> פעולת <b>CHUNK</b> מחלקת למספר נתון של חלקים, בעוד פעולת <b>SPLIT</b> מחלקת לפי גודל חלק נתון.

<table border="1" cellpadding="10" cellspacing="0" style="border-collapse: collapse; text-align: center; margin: 0 auto;"> <tr style="background-color: #4a4a4a; color: white;"> <th>פעולה</th> <th>השאלה המנחה</th> <th>פרמטר הקלט</th> <th>תוצאה (עבור טנזור בגודל 6)</th> </tr> <tr style="background-color: #e6f3ff;"> <td><strong>CHUNK</strong></td> <td>"לכמה חתיכות לחלק?"</td> <td>מספר החלקים הרצוי


(Number of Parts)</td> <td>פרמטר = 3


נקבל <b>3</b> חלקים


(גודל כל חלק יחושב כ-2)</td> </tr> <tr style="background-color: #fff3e6;"> <td><strong>SPLIT</strong></td> <td>"מה הגודל של כל חתיכה?"</td> <td>גודל כל חלק


(Size of Part)</td> <td>פרמטר = 3


נקבל חלקים בגודל <b>3</b>


(מספר החלקים יצא 2)</td> </tr> </table>


<h4>דוגמה ויזואלית - ההבדל בתוצאה</h4> נניח שיש לנו טנזור מקור באורך <b>6</b>: <span style="font-family: monospace;">[0, 1, 2, 3, 4, 5]</span>



<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; text-align: center; margin: 0 auto;"> <tr style="background-color: #4a4a4a; color: white;"> <th>מקור [6]</th> <th>CHUNK(2)


<small>רוצה 2 חלקים</small></th> <th>SPLIT(2)


<small>רוצה גודל 2</small></th> </tr> <tr> <td style="font-family: monospace;"> [0, 1, 2, 3, 4, 5] </td> <td style="font-family: monospace; background-color: #e6f3ff;"> [[0, 1, 2],


[3, 4, 5]]


<small>התוצאה: 2 חלקים


(גודל אוטומטי 3)</small> </td> <td style="font-family: monospace; background-color: #fff3e6;"> [[0, 1],


[2, 3],


[4, 5]]


<small>התוצאה: 3 חלקים


(גודל ידני 2)</small> </td> </tr> </table>


<h4>כלל הזהב 🔑</h4> <table border="2" cellpadding="15" style="border-collapse: collapse; background-color: #ffffd9; margin: 0 auto;"> <tr> <td> <strong>CHUNK:</strong> מתמקדים ב-<b>כמות</b> הפלט.


"אני רוצה בדיוק 5 חתיכות, לא אכפת לי מה הגודל."



<strong>SPLIT:</strong> מתמקדים ב-<b>גודל</b> הפלט.


"אני רוצה שכל חתיכה תהיה בגודל 5, לא אכפת לי כמה חתיכות יצאו." </td> </tr> </table>

</div></div>

In [83]:
a = torch.zeros(10, 1)
a

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [ ]:

b = torch.chunk(a, 5, 0)
b

(tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]))

In [89]:
a = torch.zeros(10,1)
a

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [90]:
b = torch.split(a,2,0)
b

(tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]),
 tensor([[0.],
         [0.]]))

The index_select method allows you to extract parts of a tensor along a given dimension. 

Note that the method takes three arguments: the tensor to operate on, 

the dimension along which to extract data, and **the tensor containing the indices**. 

(In our case, index = torch.LongTensor([0, 1]) is the tensor of indices)

In the following, we construct a 3x3 tensor, and then extract data along each of the two dimensions.

In [91]:
a = torch.FloatTensor([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
index = torch.LongTensor([0, 1])
b = torch.index_select(a, 0, index)
b

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [94]:
c = torch.index_select(a, 1, index)
c

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])

The masked_select method , illustrated in the following Listing, 

allows you to select elements given a Boolean mask.

In [132]:
a = torch.FloatTensor([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [133]:
mask = torch.ByteTensor([[0, 1, 0],[1, 1, 1],[0, 1, 0]])
mask

tensor([[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [134]:
b = torch.masked_select(a, mask.bool())
b

tensor([2., 4., 5., 6., 8.])

The squeeze method removes all dimensions with a value of one, 

as illustrated in the following Listing.

בדוגמה הבאה יש לנו טנזור של מטריצה 2 על 2 ומגדירים אותה כמימד אחד בייחס למימד שלישי

את המימד הזה הסקוויז מוחק כי אין לו משמעות רק אם היה גדול מ1

In [112]:
a = torch.zeros(2,2,1)
a

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [117]:
b = a.squeeze()
b

tensor([[0., 0.],
        [0., 0.]])

Similarly, the unsqueeze method adds a new dimension with a value of one,

In [118]:
a = torch.zeros(2,2)
a

tensor([[0., 0.],
        [0., 0.]])

In [120]:
b = torch.unsqueeze(a, 0)
b

tensor([[[0., 0.],
         [0., 0.]]])

In [121]:
c = torch.unsqueeze(a, 1)
c

tensor([[[0., 0.]],

        [[0., 0.]]])

In [122]:
d = torch.unsqueeze(a, 2)
d

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [124]:
a = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [125]:
torch.unbind(a, 0)

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [126]:
torch.unbind(a, 1)

(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))

In [130]:
a = torch.zeros(3,3)
b = torch.ones(3,3)
c = torch.rand(3,3)

d = torch.where(c > 0.5, a, b)
d

tensor([[1., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])

The any and all methods , 

illustrated in the following, 

enable you to check whether a given condition is true in any or all cases, respectively.

In [141]:
a = torch.rand(3,3)
a

tensor([[0.0280, 0.9313, 0.1309],
        [0.9551, 0.2300, 0.9094],
        [0.4696, 0.2875, 0.8773]])

In [140]:
torch.any(a > 0)

tensor(True)

In [138]:
torch.any(a > 1)

tensor(False)

In [145]:
torch.all(a > 0.1)

tensor(False)

The view method allows you to reshape tensors. 

The following Listing illustrates reshaping tensors. 

Note that using -1 as the size along some dimension implies that this is to be inferred based on the other sizes.

In [146]:
a = torch.arange(1,10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
b = a.view(3,3)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [153]:
c = a.view(3,-1)
c

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

The flatten method can be used to collapse the dimensions of a given tensor starting with a particular dimension.

In [ ]:
a = torch.ones(2,2,2,2)
a

torch.Size([2, 2, 2, 2])

In [158]:
b = torch.flatten(a)
b

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [159]:
c = torch.flatten(a, start_dim=0)
c

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [160]:
d = torch.flatten(a, start_dim=1)
d

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [162]:
e = torch.flatten(a, start_dim=2)
e

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [163]:
f = torch.flatten(a, start_dim=3)
f

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

The gather method allows us to extract values from a tensor along a given dimension 

at given positions. 

The following Listing illustrates extracting values from a tensor using gather.

In [164]:
a = torch.rand(4,4)
a

tensor([[0.8143, 0.1774, 0.0962, 0.1382],
        [0.7968, 0.3054, 0.0101, 0.5520],
        [0.7128, 0.4031, 0.9647, 0.8458],
        [0.6408, 0.3810, 0.9157, 0.1946]])

In [176]:
b = torch.LongTensor([[0,1,2,3]])
b

tensor([[0, 1, 2, 3]])

In [177]:
c = a.gather(0,b)
c

tensor([[0.8143, 0.3054, 0.9647, 0.1946]])

In [167]:
d = torch.LongTensor([[0],[1],[2],[3]])
d

tensor([[0],
        [1],
        [2],
        [3]])

In [168]:
e = a.gather(1,d)
e

tensor([[0.8143],
        [0.3054],
        [0.9647],
        [0.1946]])

the scatter method can be used to put values into a tensor along a given dimensions at given positions. 

In [178]:
a = torch.rand(4,4)
a

tensor([[0.4965, 0.9418, 0.8460, 0.1513],
        [0.6429, 0.5877, 0.7265, 0.6693],
        [0.7179, 0.1879, 0.7488, 0.7755],
        [0.0082, 0.9298, 0.2740, 0.1055]])

In [179]:
index = torch.LongTensor([[0,1,2,3]])
index

tensor([[0, 1, 2, 3]])

In [180]:
values = torch.zeros(1,4)
values

tensor([[0., 0., 0., 0.]])

In [182]:
result = a.scatter(0, index, values)
result

tensor([[0.0000, 0.9418, 0.8460, 0.1513],
        [0.6429, 0.0000, 0.7265, 0.6693],
        [0.7179, 0.1879, 0.0000, 0.7755],
        [0.0082, 0.9298, 0.2740, 0.0000]])

In [3]:
a = torch.rand(3,3)
a

tensor([[0.9425, 0.1105, 0.6955],
        [0.9560, 0.8686, 0.0707],
        [0.8769, 0.6754, 0.5727]])

### Mathematical Operations

In [4]:
b = a + a * 1e-3
b

tensor([[0.9434, 0.1106, 0.6962],
        [0.9569, 0.8694, 0.0708],
        [0.8777, 0.6761, 0.5733]])

In [6]:
torch.allclose(a,b,rtol=1e-2)

True

In [7]:
torch.allclose(a,b,rtol=1e-4)

False

In [8]:
torch.allclose(a,b,atol=1e-3)

True

The argmax and argmin methods allow you to get the index of the maximum and minimum value along a given dimension. 

In [24]:
a = torch.rand(3,3)
a

tensor([[0.9774, 0.7081, 0.9973],
        [0.8077, 0.3707, 0.0588],
        [0.7428, 0.9433, 0.3774]])

In [18]:
torch.argmax(a, dim=0)

tensor([0, 2, 0])

In [19]:
torch.argmax(a, dim=1)

tensor([2, 1, 1])

In [16]:
torch.argmin(a, dim=0)

tensor([0, 0, 1])

In [25]:
torch.argmin(a)

tensor(5)

### the argsort function

In [21]:
a = torch.rand(3,3)
a

tensor([[0.2562, 0.4554, 0.4053],
        [0.4747, 0.8706, 0.8400],
        [0.5782, 0.4983, 0.7233]])

In [22]:
torch.argsort(a, dim=0)

tensor([[0, 0, 0],
        [1, 2, 2],
        [2, 1, 1]])

In [23]:
torch.argsort(a, dim=1)

tensor([[0, 2, 1],
        [0, 2, 1],
        [1, 0, 2]])

### The cumsum method

In [26]:
a = torch.rand(3,3)
a

tensor([[0.7011, 0.8558, 0.7651],
        [0.5575, 0.3488, 0.9798],
        [0.2175, 0.8046, 0.2139]])

In [27]:
b = torch.cumsum(a, dim=0)
b

tensor([[0.7011, 0.8558, 0.7651],
        [1.2586, 1.2045, 1.7449],
        [1.4761, 2.0091, 1.9588]])

In [28]:
c = torch.cumsum(a, dim=1)
c

tensor([[0.7011, 1.5569, 2.3220],
        [0.5575, 0.9063, 1.8860],
        [0.2175, 1.0221, 1.2360]])

 ### the cumprod method allows you to compute the cumulative product along a given dimension. 

In [32]:
a = torch.rand(3,3)
a

tensor([[0.8471, 0.4151, 0.0165],
        [0.5618, 0.4814, 0.1888],
        [0.2629, 0.8422, 0.1571]])

In [35]:
b = torch.cumprod(a, dim=0)
b

tensor([[8.4707e-01, 4.1509e-01, 1.6527e-02],
        [4.7588e-01, 1.9980e-01, 3.1211e-03],
        [1.2510e-01, 1.6828e-01, 4.9029e-04]])

In [34]:
c = torch.cumprod(a, dim=1)
c

tensor([[0.8471, 0.3516, 0.0058],
        [0.5618, 0.2704, 0.0511],
        [0.2629, 0.2214, 0.0348]])

### The abs method allows you to compute the absolute value of the elements of a given tensor.

In [36]:
a = torch.tensor([[1,-1,1],[1,-1,1],[1,-1,1]])
a

tensor([[ 1, -1,  1],
        [ 1, -1,  1],
        [ 1, -1,  1]])

In [37]:
b = torch.abs(a)
b

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

### The clamp function allows you to restrict elements between a given minimum and maximum. 

In [38]:
a = torch.rand(3,3)
a

tensor([[0.0030, 0.7690, 0.7954],
        [0.9017, 0.9171, 0.6730],
        [0.9339, 0.1373, 0.4410]])

In [39]:
b = torch.clamp(a, min=0.25, max=0.50)
b

tensor([[0.2500, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.2500, 0.4410]])

### The ceil and floor functions allow you to round-up or round-down the elements of a given tensor,

In [40]:
a = torch.rand(3,3) * 100
a

tensor([[28.1335, 75.7382, 17.4544],
        [93.8355, 52.0806, 43.9208],
        [54.0521, 30.1877, 51.9916]])

In [41]:
b = torch.floor(a)
b

tensor([[28., 75., 17.],
        [93., 52., 43.],
        [54., 30., 51.]])

In [42]:
c = torch.ceil(a)
c

tensor([[29., 76., 18.],
        [94., 53., 44.],
        [55., 31., 52.]])

#### Element-Wise Mathematical Operations

<div dir="rtl" style="margin-left: -3cm;">

### Element-Wise Mathematical Operations

כעת נסקור מספר פעולות מתמטיות **איבר-איבר** (Element-Wise).<br>
פעולות אלו נקראות *איבר-איבר* משום שמבצעים **בדיוק את אותה פעולה על כל איבר** בטנזור בנפרד (למשל כפל/חיבור לכל תא במטריצה).<br>

לדוגמה, הפונקציה `mul` מאפשרת לבצע **כפל איבר-איבר**:<br>
אם יש לנו שני טנזורים באותו גודל (או גדלים שמתאימים לשידור – broadcasting), אז כל איבר בטנזור הראשון מוכפל באיבר המתאים לו בטנזור השני.<br>

כלומר, במקום כפל מטריצות (matrix multiplication), מקבלים:

* כפל של תא-בתא
* והתוצאה היא טנזור באותו מבנה (אותו shape) כמו הקלט (במקרה של גדלים זהים).

</div>



The mul function allows you to perform element-wise multiplication

In [49]:
a = torch.rand(3,3)
a

tensor([[0.6004, 0.7988, 0.5039],
        [0.8070, 0.4318, 0.4583],
        [0.5182, 0.3015, 0.4915]])

In [45]:
b = torch.FloatTensor([[0, 1, 0],[1,1,1],[0,1,0]])
b

tensor([[0., 1., 0.],
        [1., 1., 1.],
        [0., 1., 0.]])

In [46]:
c = torch.mul(a,b)
c

tensor([[0.0000, 0.1193, 0.0000],
        [0.3549, 0.9393, 0.5672],
        [0.0000, 0.0632, 0.0000]])

In [47]:
b = torch.FloatTensor([[1, 2, 1],[2,2,2],[1,2,1]])
b

tensor([[1., 2., 1.],
        [2., 2., 2.],
        [1., 2., 1.]])

In [50]:
c = torch.div(a,b)
c

tensor([[0.6004, 0.3994, 0.5039],
        [0.4035, 0.2159, 0.2291],
        [0.5182, 0.1507, 0.4915]])

### Trigonometric Operations in Tensors

In [51]:
a = torch.linspace(-1.0, 1.0, steps=10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [53]:
torch.sin(a)

tensor([-0.8415, -0.7017, -0.5274, -0.3272, -0.1109,  0.1109,  0.3272,  0.5274,
         0.7017,  0.8415])

In [54]:
torch.cos(a)

tensor([0.5403, 0.7125, 0.8496, 0.9450, 0.9938, 0.9938, 0.9450, 0.8496, 0.7125,
        0.5403])

In [56]:
torch.tan(a)

tensor([-1.5574, -0.9849, -0.6208, -0.3463, -0.1116,  0.1116,  0.3463,  0.6208,
         0.9849,  1.5574])

In [57]:
torch.atan(a)

tensor([-0.7854, -0.6610, -0.5071, -0.3218, -0.1107,  0.1107,  0.3218,  0.5071,
         0.6610,  0.7854])

### few functions that are frequently used in machine learning—namely, sigmoid, tanh, log1p (which computes y = log(1+x)), erf (Gaussian error function), and erfinv (inverse Gaussian error function).

In [58]:
a = torch.linspace(-1.0, 1.0, steps=10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [59]:
torch.sigmoid(a)

tensor([0.2689, 0.3148, 0.3646, 0.4174, 0.4723, 0.5277, 0.5826, 0.6354, 0.6852,
        0.7311])

In [60]:
torch.tanh(a)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

In [61]:
torch.log1p(a)

tensor([   -inf, -1.5041, -0.8109, -0.4055, -0.1178,  0.1054,  0.2877,  0.4418,
         0.5754,  0.6931])

In [62]:
torch.erfinv(a)

tensor([   -inf, -0.8631, -0.5407, -0.3046, -0.0988,  0.0988,  0.3046,  0.5407,
         0.8631,     inf])

### Comparison Operations for Tensors

In [63]:
a = torch.rand(3,3)
a

tensor([[0.9928, 0.5486, 0.3055],
        [0.8280, 0.2568, 0.8970],
        [0.6115, 0.7126, 0.9543]])

In [64]:
b = torch.rand(3,3)
b

tensor([[0.9853, 0.5421, 0.2702],
        [0.8763, 0.5715, 0.7937],
        [0.1068, 0.2762, 0.6061]])

In [65]:
torch.ge(a,b)

tensor([[ True,  True,  True],
        [False, False,  True],
        [ True,  True,  True]])

In [66]:
torch.le(a,b)

tensor([[False, False, False],
        [ True,  True, False],
        [False, False, False]])

In [67]:
torch.ne(a,b)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [68]:
torch.eq(a,b)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

#### Linear Algebraic Operations

The matmul function allows you to multiply two tensors.

In [80]:
a = torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [81]:
b = torch.ones(3,2)
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [82]:
torch.matmul(a,b)

tensor([[3., 3.],
        [3., 3.]])

The addbmm function (where bmm stands for batch matrix-matrix product) 
<br>allows you to perform the computation p * m + q * [a1 * b1 + a2 * b2 + ...], 
<br>where p and q are scalars, and m, a1, b1, a2, and b2 are tensors. 
<br>Note that the addbmm function takes parameters p and q with default values 
<br>equal to one and that tensors such as a1 and a2 are provided by stacking them along the first dimension. 

In [83]:
a = torch.ones(2, 2, 3)
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [84]:
b = torch.ones(2, 3, 2)
b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [85]:
m = torch.ones(2,2)
m

tensor([[1., 1.],
        [1., 1.]])

In [86]:
torch.addbmm(2, m, 3, a, b)

tensor([[20., 20.],
        [20., 20.]])

In [87]:
torch.addbmm(1, m, 1, a, b)

tensor([[7., 7.],
        [7., 7.]])

In [88]:
torch.addbmm(m, a, b)

tensor([[7., 7.],
        [7., 7.]])

The addmm function is a non-batch version of addbmm 
<br>that allows you to perform the computation p * m + q * a * b, 
<br>where p and q are scalars, and m, a, and b are tensors. 
<br>Note that the addmm function takes parameters p and q with default values equal to one.

In [89]:
a = torch.ones(2, 3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [90]:
b = torch.ones(3, 2)
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [91]:
m = torch.ones(2,2)
m

tensor([[1., 1.],
        [1., 1.]])

In [92]:
torch.addmm(m, a, b)

tensor([[4., 4.],
        [4., 4.]])

In [93]:
torch.addmm(2, m, 3, a, b)

tensor([[11., 11.],
        [11., 11.]])

In [98]:
torch.addmm(1, m, 1, a, b)

tensor([[4., 4.],
        [4., 4.]])